
package com.example.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DoMathService", targetNamespace = "http://webservice.example.com/", wsdlLocation = "http://localhost:9090/SOAPservices/jaxws/domath?wsdl")
public class DoMathService
    extends Service
{

    private final static URL DOMATHSERVICE_WSDL_LOCATION;
    private final static WebServiceException DOMATHSERVICE_EXCEPTION;
    private final static QName DOMATHSERVICE_QNAME = new QName("http://webservice.example.com/", "DoMathService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/SOAPservices/jaxws/domath?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DOMATHSERVICE_WSDL_LOCATION = url;
        DOMATHSERVICE_EXCEPTION = e;
    }

    public DoMathService() {
        super(__getWsdlLocation(), DOMATHSERVICE_QNAME);
    }

    public DoMathService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOMATHSERVICE_QNAME, features);
    }

    public DoMathService(URL wsdlLocation) {
        super(wsdlLocation, DOMATHSERVICE_QNAME);
    }

    public DoMathService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOMATHSERVICE_QNAME, features);
    }

    public DoMathService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DoMathService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DoMath
     */
    @WebEndpoint(name = "DoMathPort")
    public DoMath getDoMathPort() {
        return super.getPort(new QName("http://webservice.example.com/", "DoMathPort"), DoMath.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DoMath
     */
    @WebEndpoint(name = "DoMathPort")
    public DoMath getDoMathPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.example.com/", "DoMathPort"), DoMath.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOMATHSERVICE_EXCEPTION!= null) {
            throw DOMATHSERVICE_EXCEPTION;
        }
        return DOMATHSERVICE_WSDL_LOCATION;
    }

}
