
package com.example.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SaySomethingService", targetNamespace = "http://soap_thing_take_12312/", wsdlLocation = "http://localhost:9000/soap_thing_take_12312/test/hello?wsdl")
public class SaySomethingService
    extends Service
{

    private final static URL SAYSOMETHINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException SAYSOMETHINGSERVICE_EXCEPTION;
    private final static QName SAYSOMETHINGSERVICE_QNAME = new QName("http://soap_thing_take_12312/", "SaySomethingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/soap_thing_take_12312/test/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAYSOMETHINGSERVICE_WSDL_LOCATION = url;
        SAYSOMETHINGSERVICE_EXCEPTION = e;
    }

    public SaySomethingService() {
        super(__getWsdlLocation(), SAYSOMETHINGSERVICE_QNAME);
    }

    public SaySomethingService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SAYSOMETHINGSERVICE_QNAME, features);
    }

    public SaySomethingService(URL wsdlLocation) {
        super(wsdlLocation, SAYSOMETHINGSERVICE_QNAME);
    }

    public SaySomethingService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SAYSOMETHINGSERVICE_QNAME, features);
    }

    public SaySomethingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SaySomethingService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SaySomething
     */
    @WebEndpoint(name = "SaySomethingPort")
    public SaySomething getSaySomethingPort() {
        return super.getPort(new QName("http://soap_thing_take_12312/", "SaySomethingPort"), SaySomething.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SaySomething
     */
    @WebEndpoint(name = "SaySomethingPort")
    public SaySomething getSaySomethingPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap_thing_take_12312/", "SaySomethingPort"), SaySomething.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAYSOMETHINGSERVICE_EXCEPTION!= null) {
            throw SAYSOMETHINGSERVICE_EXCEPTION;
        }
        return SAYSOMETHINGSERVICE_WSDL_LOCATION;
    }

}
