
package com.example.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SaySomething", targetNamespace = "http://soap_thing_take_12312/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SaySomething {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap_thing_take_12312/SaySomething/saySomethingRequest", output = "http://soap_thing_take_12312/SaySomething/saySomethingResponse")
    public String saySomething(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
