
package com.example.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WriteNumberService", targetNamespace = "http://soap_thing_take_12312/", wsdlLocation = "http://localhost:9000/soap_thing_take_12312/test/number?wsdl")
public class WriteNumberService
    extends Service
{

    private final static URL WRITENUMBERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WRITENUMBERSERVICE_EXCEPTION;
    private final static QName WRITENUMBERSERVICE_QNAME = new QName("http://soap_thing_take_12312/", "WriteNumberService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/soap_thing_take_12312/test/number?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WRITENUMBERSERVICE_WSDL_LOCATION = url;
        WRITENUMBERSERVICE_EXCEPTION = e;
    }

    public WriteNumberService() {
        super(__getWsdlLocation(), WRITENUMBERSERVICE_QNAME);
    }

    public WriteNumberService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WRITENUMBERSERVICE_QNAME, features);
    }

    public WriteNumberService(URL wsdlLocation) {
        super(wsdlLocation, WRITENUMBERSERVICE_QNAME);
    }

    public WriteNumberService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WRITENUMBERSERVICE_QNAME, features);
    }

    public WriteNumberService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WriteNumberService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WriteNumber
     */
    @WebEndpoint(name = "WriteNumberPort")
    public WriteNumber getWriteNumberPort() {
        return super.getPort(new QName("http://soap_thing_take_12312/", "WriteNumberPort"), WriteNumber.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WriteNumber
     */
    @WebEndpoint(name = "WriteNumberPort")
    public WriteNumber getWriteNumberPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap_thing_take_12312/", "WriteNumberPort"), WriteNumber.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WRITENUMBERSERVICE_EXCEPTION!= null) {
            throw WRITENUMBERSERVICE_EXCEPTION;
        }
        return WRITENUMBERSERVICE_WSDL_LOCATION;
    }

}
