
package com.example.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

import com.example.model.Person;
import com.sun.xml.ws.runtime.config.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloGenerator", targetNamespace = "http://webservice.example.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloGenerator {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.example.com/HelloGenerator/helloRequest", output = "http://webservice.example.com/HelloGenerator/helloResponse")
    public String hello(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.services.Person
     */
    @WebMethod(operationName = "HelloPerson")
    @WebResult(partName = "return")
    @Action(input = "http://webservice.example.com/HelloGenerator/HelloPersonRequest", output = "http://webservice.example.com/HelloGenerator/HelloPersonResponse")
    public Person helloPerson(
        @WebParam(name = "arg0", partName = "arg0")
        Person arg0);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.example.com/HelloGenerator/greetedRequest", output = "http://webservice.example.com/HelloGenerator/greetedResponse")
    public boolean greeted();

}
