server:
  port: ${PORT:8761}

eureka:
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: false
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10

spring:
  boot:
    admin:
      context-path: /admin
